server:
  port: 8695
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 970923
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.zjh.entity
file:
  real:
    path:  E:/idea_projects/final/cmfz/src/main/webapp
